"""add

Revision ID: 1bdceeea6d45
Revises: f3b1ce8a729d
Create Date: 2026-04-16 19:26:10.636339

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1bdceeea6d45'
down_revision = 'f3b1ce8a729d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_user',
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('animal_count', sa.Integer(), nullable=True),
    sa.Column('district', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('preferred_language', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('main_goal', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_fully_onboarded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_user_phone'), 'whatsapp_user', ['phone'], unique=True)
    op.create_table('whatsapp_message',
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['whatsapp_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_message_user_id'), 'whatsapp_message', ['user_id'], unique=False)
    op.alter_column('livestock_image', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('livestock_image', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_whatsapp_message_user_id'), table_name='whatsapp_message')
    op.drop_table('whatsapp_message')
    op.drop_index(op.f('ix_whatsapp_user_phone'), table_name='whatsapp_user')
    op.drop_table('whatsapp_user')
    # ### end Alembic commands ###
