"""add

Revision ID: 241a18a965e7
Revises: 5a57f885096f
Create Date: 2026-05-05 17:09:15.617791

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '241a18a965e7'
down_revision = '5a57f885096f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('whatsapp_message_user_id_fkey'), 'whatsapp_message', type_='foreignkey')
    op.create_foreign_key(None, 'whatsapp_message', 'whatsapp_user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whatsapp_message', type_='foreignkey')
    op.create_foreign_key(op.f('whatsapp_message_user_id_fkey'), 'whatsapp_message', 'whatsapp_user', ['user_id'], ['id'])
    # ### end Alembic commands ###
