"""add image_url to livestock

Revision ID: 2c6c69b12079
Revises: b7f7c95015c1
Create Date: 2026-03-28 00:22:31.926961

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2c6c69b12079'
down_revision = 'b7f7c95015c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livestock', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livestock', 'image_url')
    # ### end Alembic commands ###
