"""connect

Revision ID: 5a57f885096f
Revises: 1bdceeea6d45
Create Date: 2026-04-19 00:34:39.269519

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5a57f885096f'
down_revision = '1bdceeea6d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_user', sa.Column('linked_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'whatsapp_user', 'user', ['linked_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whatsapp_user', type_='foreignkey')
    op.drop_column('whatsapp_user', 'linked_user_id')
    # ### end Alembic commands ###
