"""Add active_sickness_animal_id to whatsapp_user

Revision ID: 71934b35522e
Revises: b3a1bad08315
Create Date: 2026-07-22 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71934b35522e'
down_revision = 'b3a1bad08315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_user', sa.Column('active_sickness_animal_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'whatsapp_user', 'livestock', ['active_sickness_animal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whatsapp_user', type_='foreignkey')
    op.drop_column('whatsapp_user', 'active_sickness_animal_id')
    # ### end Alembic commands ###
