"""Describe what changed

Revision ID: 84eb1ed7e61b
Revises: 11cf5a7ee699
Create Date: 2026-03-21 22:30:40.946721

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '84eb1ed7e61b'
down_revision = '11cf5a7ee699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('size_hectares', sa.Float(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('farm_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vet_profile',
    sa.Column('licence_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('specialisations', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('availability_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('livestock',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('tag_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('breed', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('acquired_date', sa.Date(), nullable=True),
    sa.Column('species', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('health_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_observation',
    sa.Column('body_temp_celsius', sa.Float(), nullable=True),
    sa.Column('heart_rate_bpm', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('symptoms', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('symptom_duration_days', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('livestock_id', sa.Uuid(), nullable=False),
    sa.Column('logged_by', sa.Uuid(), nullable=False),
    sa.Column('appetite_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activity_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('milk_production', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['livestock_id'], ['livestock.id'], ),
    sa.ForeignKeyConstraint(['logged_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment',
    sa.Column('treatment_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('drug_used', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('dosage', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('date_given', sa.Date(), nullable=False),
    sa.Column('outcome_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('livestock_id', sa.Uuid(), nullable=False),
    sa.Column('logged_by', sa.Uuid(), nullable=False),
    sa.Column('administered_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['livestock_id'], ['livestock.id'], ),
    sa.ForeignKeyConstraint(['logged_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccination',
    sa.Column('vaccine_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('date_given', sa.Date(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('livestock_id', sa.Uuid(), nullable=False),
    sa.Column('logged_by', sa.Uuid(), nullable=False),
    sa.Column('administered_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['livestock_id'], ['livestock.id'], ),
    sa.ForeignKeyConstraint(['logged_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vet_request',
    sa.Column('farmer_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('livestock_id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('vet_id', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('urgency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['livestock_id'], ['livestock.id'], ),
    sa.ForeignKeyConstraint(['vet_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vet_response',
    sa.Column('diagnosis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('treatment_recommendation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('drug_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('dosage', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('vet_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vet_request_id', sa.Uuid(), nullable=False),
    sa.Column('vet_id', sa.Uuid(), nullable=False),
    sa.Column('response_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vet_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vet_request_id'], ['vet_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vet_request_id')
    )
    # server_default backfills existing rows before the NOT NULL constraint is applied.
    op.add_column('user', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='farmer'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_table('vet_response')
    op.drop_table('vet_request')
    op.drop_table('vaccination')
    op.drop_table('treatment')
    op.drop_table('health_observation')
    op.drop_table('livestock')
    op.drop_table('vet_profile')
    op.drop_table('farm')
    # ### end Alembic commands ###
