"""check

Revision ID: ab39d02f27fd
Revises: 241a18a965e7
Create Date: 2026-06-17 22:23:36.303921

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ab39d02f27fd'
down_revision = '241a18a965e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_user', sa.Column('is_adding_animal', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('whatsapp_user', 'is_adding_animal', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_user', 'is_adding_animal')
    # ### end Alembic commands ###
