"""Add district to user

Revision ID: b3a1bad08315
Revises: 8f5bb8117157
Create Date: 2026-06-27 22:23:57.260147

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b3a1bad08315'
down_revision = '8f5bb8117157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('district', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'district')
    # ### end Alembic commands ###
