name: Deploy Backend to Azure via GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/vvet-backend:latest
          # Change to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          docker build -t $IMAGE_ID ./backend
          docker push $IMAGE_ID
